[package]
name = "rust-study"
version = "0.1.0"
authors = ["heesungyang"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4"
chrono = "0.4.19"
chrono-tz = "0.6.1"